# Generated by Django 6.0.6 on 2026-08-05 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('Lab Result', 'Lab Result'), ('Prescription', 'Prescription'), ('Doctor Note', 'Doctor Note'), ('Imaging', 'Imaging / X-Ray'), ('Vaccination', 'Vaccination Record'), ('Other', 'Other')], default='Lab Result', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_records/')),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('date_uploaded', models.DateField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='members.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
